name: CW-og
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.1.0
  - torchvision=0.3.0
  - cudatoolkit=10.0
  - numpy
  - scikit-learn
  - scikit-image
  - matplotlib
  - pillow
  - seaborn
  - pip
  - pip:
    - tqdm
