name: QCW
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.5
  - torchvision=0.20
  - pytorch-cuda=12.1
  - numpy=1.26
  - pandas=2.2
  - scikit-learn=1.6
  - scikit-image=0.25
  - matplotlib=3.10
  - pillow>=11.0
  - seaborn=0.13
  - opencv=4.10
  - tensorboard=2.19
  - prompt_toolkit=3.0
  - rich>=14.0
  - ruamel.yaml>=0.18
  - pip:
      - tqdm>=4.67
      - pycocotools>=2.0
