name: QCW
channels:
    - pytorch
    - nvidia
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - pytorch-cuda=12.1
    - pytorch
    - cudatoolkit
    - torchvision
    - numpy
    - scikit-learn
    - scikit-image
    - matplotlib
    - pillow
    - seaborn
    - opencv
    - tensorboard
    - prompt_toolkit
    - rich
    - ruamel.yaml
    - pip:
        - tqdm
